<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-title">
    <h1><?php echo Mage::helper('formprocessor')->__('Sample Form'); ?></h1>
</div>

<form action="<?php echo Mage::helper('formprocessor')->getFormActionUrl(Mage::helper('formprocessor')->getConfig('sample/form_id')); ?>" id="sampleForm" method="post" enctype="multipart/form-data">

    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('formprocessor')->__('Contact Information') ?></h2>
        <label for="visitor_name" class="required"><em>*</em><?php echo Mage::helper('formprocessor')->__('Name') ?></label>
        <div class="input-box">
            <input type="text" name="visitor_name" id="visitor_name" title="<?php echo Mage::helper('formprocessor')->__('Name') ?>" value="<?php echo $this->htmlEscape(Mage::helper('formprocessor')->getUserName()) ?>" class="input-text required-entry" />
        </div>
        <label for="visitor_email" class="required"><em>*</em><?php echo Mage::helper('formprocessor')->__('Email') ?></label>
        <div class="input-box">
            <input type="text" name="visitor_email" id="visitor_email" title="<?php echo Mage::helper('formprocessor')->__('Email') ?>" value="<?php echo $this->htmlEscape(Mage::helper('formprocessor')->getUserEmail()) ?>" class="input-text required-entry validate-email" />
        </div>
        <label for="prescription"><?php echo Mage::helper('formprocessor')->__('Prescription') ?></label>
        <div class="input-box">
            <input type="file" name="prescription" id="prescription" title="<?php echo Mage::helper('formprocessor')->__('Prescription'); ?>" />
        </div>
    </div>

    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('formprocessor')->__('* Required Fields'); ?></p>
        <button type="submit" class="btn btn-primary"><?php echo Mage::helper('formprocessor')->__('Submit'); ?></button>
    </div>

</form>

<script type="text/javascript">
    /* Form Validation */
    //<![CDATA[
    var sampleForm = new VarienForm('sampleForm', true);
    //]]>
</script>

<?php if (Mage::helper('formprocessor')->getConfig('sample/ajax')): ?>

    <script type="text/javascript">
        /* AJAX Submit */
        jQuery(document).ready(function($) {
            $('#sampleForm').on('submit', function(e) {
                /* Copy the form into a var */
                var form = $(this);
                /* Check to see if Prototype JS has left any validation errors */
                if (form.find('input[type=text],textarea,select').hasClass('validation-failed')) {
                    var validation = false;
                } else {
                    var validation = true;
                }
                /* If no validation errors - submit */
                if (validation) {
                    var post_url = form.attr('action');
                    var post_data = form.serialize();
                    $.ajax({
                        type: 'POST',
                        url: post_url,
                        data: post_data,
                        dataType: 'json',
                        beforeSend: function() {
                            $('.buttons-set button').text('<?php echo Mage::helper('formprocessor')->__('Please wait...'); ?>').attr('disabled', true);
                        },
                        success: function(data) {
                            var html = '<div class="alert alert-' + data.status + '"><button type="button" class="close" data-dismiss="alert">×</button><div><div><span>' + data.message + '</span></div></div></div>';
                            $('.col-main').prepend(html);
                        },
                        error: function() {
                        },
                        complete: function() {
                            $('.buttons-set button').text('<?php echo Mage::helper('formprocessor')->__('Submit'); ?>').attr('disabled', false);
                        }
                    });
                    return false;
                }
            });
        });
    </script>

<?php endif; ?>